spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/restful
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true  # 주석 추가로 쿼리 확인 가능

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  refresh-token-validity-in-seconds: 1209600 # 14일
  access-token-validity-in-seconds: 43200 # 12시간